# Source: https://github.com/stabbyfork/stuff/blob/main/colorpicker

# To reset this config to defaults, delete the file and click 'Settings' again.

# Whether to generate log files or not. Log files have dates and times included, with extra information. (valid values: 'true','false'; default: 'false')
generateLogFiles = false

# Include time in the standard (window) output. (valid values: 'true','false'; default: 'true')
showTime = true


